# Generated by Django 4.0.6 on 2022-07-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='master',
            name='phone',
        ),
    ]
